### ISSUE TITLE
Can only craft deck boards with default:wood

### ISSUE THREAD

**Issue by NathanSalapat** [DonBatman/mydeck#2]
If I use pinewood planks I can't craft anything in the machine. Maybe the recipe should be changed to group:wood?

**Comment by DonBatman** [comment]
It was bugging me so I pulled out my laptop and did it.
Decks are now flammable and use group wood.

**Comment by NathanSalapat** [comment]
Thank you.

P.S.
not sure how familiar you are with Github issues, but now that it is fixed you should mark them as closed. :)

**Comment by DonBatman** [comment]
I never knew about that. I will learn it.
Thanks

**Comment by NathanSalapat** [comment]
I actually closed both for you, thought I'd mention it for future reference.

On Sun, Apr 12, 2015 at 3:27 PM, DonBatman <notifications@github.com> wrote:

> I never knew about that. I will learn it.
> Thanks
>
> On Sun, Apr 12, 2015 at 1:23 PM, Nathan Salapat <notifications@github.com>
> wrote:
>
> > Thank you.
> >
> > P.S.
> > not sure how familiar you are with Github issues, but now that it is
> fixed
> > you should mark them as closed. :)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/DonBatman/mydeck/issues/2#issuecomment-92119919>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DonBatman/mydeck/issues/2#issuecomment-92121061>.
>



-- 
God Loves You!!!

John 3:16
For God so loved the world, that he gave his only begotten Son, that
whosoever believeth in him should not perish, but have everlasting life.

**Comment by DonBatman** [comment]
I see the issues thing on github now. You are the first to have an issue
with one of my mods. lol
Thank you for pointing them out. I love how the community helps each other.
