### ISSUE TITLE
A few tips

### ISSUE THREAD

**Issue by TeTpaAka** [DonBatman/mydeck#3]
https://github.com/DonBatman/mydeck/blob/master/beam.lua#L30-L64
nodea can't have multiple different values. You should use else if.
Same for nodeu. Also move the nodeu checks together.
Why do you first set the nodea to air? And why check twice the same?

https://github.com/DonBatman/mydeck/blob/master/deckboards.lua#L42-L115
Same here.

https://github.com/DonBatman/mydeck/blob/master/joists.lua#L37-L48
And here.

https://github.com/DonBatman/mydeck/blob/master/joists.lua#L88-L99
And here.

https://github.com/DonBatman/mydeck/blob/master/machine.lua#L56-L71
You could do:
```
if inv:is_empty("ingot") and 
   inv:is_empty("res") and  ... then
    return true
else
    return false
end
```
Then you would have less code and it would be easier to add/remove something.

https://github.com/DonBatman/mydeck/blob/master/machine.lua#L3-L5
Why tables?

https://github.com/DonBatman/mydeck/blob/master/machine.lua#L361-L377
Move the table out.

https://github.com/DonBatman/mydeck/blob/master/piles.lua#L109-L130
Use if else

https://github.com/DonBatman/mydeck/blob/master/stain.lua#L4-L20
You already made this table. Try putting it as subtable in a global mydeck table.

https://github.com/DonBatman/mydeck/blob/master/stain.lua#L48-L210
Use if else

https://github.com/DonBatman/mydeck/blob/master/stain.lua#L252-L318
Use if else

https://github.com/DonBatman/mydeck/blob/master/stain.lua#L1441-L1462
Use if else

Again, no offence intended.

**Comment by MilesDyson-Research** [comment]
thank you thank you! this is a huge help, i forwarded this to Batman and 
he is working on the changes... ;)
